# Generated by Django 4.0.1 on 2022-03-08 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('content', models.TextField(blank=True, verbose_name='Текст комментария')),
                ('is_published', models.BooleanField(default=False, verbose_name='Статус')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_posts', to='blog.posts', verbose_name='Описание')),
            ],
        ),
    ]
